# Generated by Django 3.1 on 2020-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='border',
            field=models.PositiveSmallIntegerField(choices=[(0, 'white'), (1, 'black'), (2, 'yellow'), (2, 'red')], default=0),
        ),
    ]
